#权限:拥有cd.bypass权限的玩家可以执行位于禁止列表内的指令; 
#拥有cd.reload权限的玩家可以执行/cmbreload指令来重新加载配置文件;
#拥有自定义权限的玩家或者组可以执行对应的指令

#无权限玩家执行被禁止的指令时的提示
message: '&8[&c该指令已被锁定,你没有权限使用!&8]'

#但无权限玩家试图重新加载配置文件时的提示
ondeny: '&8[&c你没有权限使用这个指令!&8]'

#配置文件重新加载的提示
onreload: '&8[&a已成功加载配置文件!&8]'

#禁止使用的指令列表
#指令或者指令段与相应权限间使用"^"分开
commands:
  - 'pl'
  - 'bukkit:pl'
  - 'pay *^cd.cdpay'