name: commandeny
main: cn.mctime.ferrinweb.main
version: 1.1
author: ferrinweb

commands:
  cdreload:
    usage: /<command>
    description: 重新加载配置文件
    permission: cd.reload
    
permissions:
  cd.*:
    default: false
  cd.bypass: 
    default: false
  cd.reload: 
    default: op